# Generated by Django 5.2.14 on 2026-06-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidur', models.FloatField()),
                ('belajar', models.FloatField()),
                ('bermain', models.FloatField()),
                ('sosmed', models.FloatField()),
                ('kopi', models.FloatField()),
                ('olahraga', models.FloatField()),
                ('laptop', models.IntegerField()),
                ('hasil_ipk', models.FloatField()),
                ('waktu_prediksi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
