# Generated by Django 5.2.14 on 2026-06-02 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionlog',
            name='waktu_prediksi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
