# Generated by Django 5.2.14 on 2026-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_predictionlog_waktu_prediksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umur', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('rata2_tidur_hari', models.FloatField()),
                ('rata2_belajar_hari', models.FloatField()),
                ('rata2_bermain_game_hari', models.FloatField()),
                ('rata2_buka_sosmed_hari', models.FloatField()),
                ('jumlah_kopi_hari', models.IntegerField()),
                ('jumlah_matcha_hari', models.IntegerField()),
                ('jumlah_ukm', models.IntegerField()),
                ('jarak_kampus_km', models.FloatField()),
                ('asal_sekolah', models.CharField(max_length=20)),
                ('rata2_olahraga_hari', models.FloatField()),
                ('memiliki_laptop', models.IntegerField()),
                ('bekerja', models.IntegerField()),
                ('ipk', models.FloatField()),
                ('ipk_group', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Data Mahasiswa',
            },
        ),
    ]
